# Generated by Django 5.1.4 on 2025-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_event_is_past_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tasks',
        ),
        migrations.AddField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(max_length=20000),
        ),
    ]
