# Generated by Django 5.1.4 on 2025-05-25 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_remove_event_tasks_event_is_cancelled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='executor',
        ),
        migrations.AddField(
            model_name='tasks',
            name='executor',
            field=models.ManyToManyField(blank=True, related_name='executed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
