# Generated by Django 5.1.4 on 2025-05-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_remove_tasks_executor_tasks_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
