# Generated by Django 5.1.4 on 2025-05-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_alter_event_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_past',
            field=models.BooleanField(default=False),
        ),
    ]
